name: Keep Upstash Alive

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
  workflow_dispatch:

jobs:
  ping-upstash:
    runs-on: ubuntu-latest
    environment: production
    env:
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
    steps:
      - name: Ping Upstash
        run: |
          curl ${UPSTASH_REDIS_REST_URL}GET/foo -H "Authorization: Bearer $UPSTASH_REDIS_REST_TOKEN" -H "Upstash-Encoding: base64"
